languages = {
"english":
    {
    "firstwelcome1":"Hello, dear friend! It's the first time you are using me, so let me help you.",
    "firstwelcome2":"I will show you where you can have fun and get your pizza dosage back to normal!",
    "firstwelcome3":"Type \'/help\' for additional commands & info!",
    "welcome1": "Welcome back!",
    "welcome2": "Felling hungry again, eh?",
    "settingsMsg":"This is a settings menu. You can change the city or language",
    "initstage0" : "Choose, what you would like to visit today:",
    "showmore" : "Show 2 more",
    "toprestsaround" : "Show top restaurants",
    "offers" : "Special offers",
    "maintenance": "We are working on this function :]",
    "returning": "Returning home...",
    "initstage4":"Hungry, eh?",
    "restaurants":"Restaurants",
    "unknown":"Unknown command. Type '/help' to see available commands",
    "home":"Home",
    "showmap":"Show on map",
    "opened":", opened ",
    "endoflist": "The end!",
    "address":". Address: ",
    "openedLocal" : "openedEn",
    "language":"Language",
    "city":"City",
    "call":"Call",
    "citychoice":"Let's choose which city you're in:",
    "parnu":"Pärnu",
    "tallinn":"Tallinn",
    "menu":"Menu",
    },
"estonian":
    {
    "firstwelcome1":"Tere! See on sinu esimene kord siin! Ma näitan sulle, kuidas mind kasutada!",
    "firstwelcome2":"Ma näitan kohad, kus saad oma kõhu täis teha!",
    "firstwelcome3":"Kirjuta \'/help\', kui tahad vaadata mis käsud ma aru saan",
    "settingsMsg":"See on seadmete menüü. Saad vahetada oma linna või keelt",
    "initstage0" : "Vali, kuhu taha minna täna:",
    "showmore" : "Näita veel 2",
    "toprestsaround" : "Näita parimad restoranid",
    "offers" : "Pakkumised",
    "maintenance": "See praegu ei tööta :]",
    "returning": "Tagasi menüüsse...",
    "initstage4":"Süüa tahad, jah?",
    "restaurants":"Restoraanid",
    "unknown":"Ma ei tea sellist sõnu. Kirjuta '/help', et vaadata, mis käsud ma aru saan",
    "home":"Tagasi",
    "showmap":"Näita kardil",
    "opened":", avatud ",
    "endoflist": "Lõpp!",
    "address":". Address: ",
    "openedLocal" : "openedEt",
    "language":"Keel",
    "city":"Linn",
    "call":"Helista",
    "citychoice":"Vali, mis linnas praegu oled:",
    "parnu":"Pärnu",
    "tallinn":"Tallinn",
    "menu":"Menüü",
       },

}