restaurants = {


"wesset" : {
            'name': "Villa Wesset",
            'openedEn': "Sun-Thu 8:00-22:00; Fri-Sat 8:00-24:00",
            'openedEt': "P-N 8:00-22:00; R-L 8:00-24:00",
            'openedRu': "Вс-Чт 8:00-22:00; Пт-Сб 8:00-24:00",
            'address': "Supeluse 26",
            'latitude': "58.378183",
            'longitude' : '24.499404',
            'image': "https://static1.visitestonia.com/images/3022581/IMG_9779_.jpg",
            'priority': 100, # пускай всегда 100 будет
            'phone': '+372 697 2500',
            'link': 'http://wesset.ee/',
            #'@' : '@wesset', #частые посетители могут быстрее найти любимый ресторан
            'town' : 'parnu',
            'type' : ['/restaurant' , '/euro' , '/whine'] ,


    },

"hea maa" : {
            'name' : "Hea Maa",
            'openedEn': "Mon-Sat 12:00-23:00; Sun - Closed",
            'openedEt': "E-L 12:00-23:00; P - Suletud",
            'openedRu': "Пн-Сб 12:00-23:00; Вс - Закрыто",
            'address': "Nikolai 3",
            'latitude': "58.3766032",
            'longitude' : '24.4938295',
            'image': "https://static2.visitestonia.com/images/3047070/13620211_1331532913542185_8921821791305399615_n_.jpg" ,
            'link' : "http://www.heamaa.ee/",
            'priority': 100 ,
            'phone' : "+37253435858" ,
            'town' : 'parnu',
            'type' : ['/restaurant' , '/euro' , '/whine'] ,
},

"lime lounge" : {
            'name': "Lime Lounge",
            #'openedEn': "Mon-Sat 12:00-23:00; Sun - Closed",
            #'openedEt': "E-L 12:00 - 23:00; P - Suletud",
            #'openedRu': "Пн-Сб 12:00-23:00; Вс - Закрыто",
            'address': "Hommiku 17",
            'latitude': "58.3844604",
            'longitude' : '24.5018452',
            'image': "https://media-cdn.tripadvisor.com/media/photo-s/02/b2/4f/71/chocolate-fondant-with.jpg",
            'priority': 100,
            'phone' : '+3724492190',
            'link' : 'http://www.limelounge.ee/',
            'town' : 'parnu',
            'type' : ['/restaurant' , '/lounge' , '/whine'] ,
},


"seegi maja" : {
            'name': "Seegi Maja",
            #'openedEn': "Mon-Sat 12:00-23:00; Sun - Closed",
            #'openedEt': "E-L 12:00-23:00; P - Suletud",
            #'openedRu': "Пн-Сб 12:00-23:00; Вс - Закрыто",
            'address': "Hospidali 1",
            'latitude': "58.3854475",
            'longitude' : '24.501093',
            'image': "http://parnurestaurantweek.ee/wp-content/uploads/2018/01/cropped-gdfgd.jpg",
            'priority': 100,
            'phone' : '+3724430550',
            'link' : 'http://www.stpeterburg.ee/seegi-maja-restoran/',
            'town' : 'parnu',
            'type' : ['/restaurant' , '/whine'] ,
},

"edelweiss" : {
            'name': "Edelweiss",
            'openedEn': "Mon-Sun 11:00-24:00",
            'openedEt': "E-P 11:00-24:00",
            'openedRu': "Пн-Сб 12:00-24:00; Вс - Закрыто",
            'address': "Hospidali 1",
            'latitude': "58.3837507",
            'longitude' : '24.4972457',
            'image': "https://www.minuvalik.ee/actimg/2013337964/l/001.jpg",
            'priority': 100,
            'phone' : '+3724420600',
            'link' : 'http://www.edelweiss.ee/',
            'town' : 'parnu',
            'type' : ['/restaurant'] ,

},

"mahedik cafe" : {
            'name' : "Mahedik Cafe",
            'openedEn' : "Mon-Thu 09:00-22:00; Fri 09:00-24:00; Sat-Sun 10:00-24:00",
            'openedEt' : "E-N 09:00-22:00; R 09:00-24:00; L-P 10:00-24:00",
            'openedRu' : "Пн-Чт 09:00-22:00; Пт 09:00-24:00; Сб-Вс 10:00-24:00",
            'address' : "Pühavaimu 20",
            'latitude' : "58.3842432",
            'longitude' : '24.4993116',
            'image' : "https://media-cdn.tripadvisor.com/media/photo-s/04/71/ba/d1/mahedik-cafe.jpg",
            'priority' : 100,
            'phone' : '+3724425393',
            'link' : 'http://www.mahedik.ee/',
            'town' : 'parnu',
            'type' : ['/cafe'] ,

},

"cafe xs" : {
            'name': "Cafe XS",
            #'openedEn': "Mon-Sun 11:00-24:00",
            #'openedEt': "E-P 11:00-24:00",
            #'openedRu': "Пн-Сб 12:00-23:00; Вс - Закрыто",
            'address': "Munga 2",
            'latitude': "58.3850794",
            'longitude' : '24.4965539',
            'image': "https://scontent-arn2-1.xx.fbcdn.net/v/t1.0-9/483487_511744562194426_209627579_n.jpg?_nc_cat=0&oh=3583de7d573f8ace281cd93fa93729b3&oe=5B551E48",
            'priority': 100,
            'phone' : '+3724431316',
            'link' : 'https://www.cafexs.ee/',
            'town' : 'parnu',
            'type' : ['/cafe'],

},

"steffani" : {
            'name': "Steffani Pizza",
            #'openedEn': "Mon-Sun 11:00-24:00",
            #'openedEt': "E-P 11:00-24:00",
            #'openedRu': "Пн-Сб 12:00-23:00; Вс - Закрыто",
            'address': "Nikolai 24",
            'latitude': "58.3833726",
            'longitude' : '24.4978615',
            'image': "https://s.err.ee/photo/crop/2013/06/07/205408had71t28.jpg",
            'priority': 100,
            'phone' : '+3724431170',
            'link' : 'http://steffani.ee/et/esileht/',
            'town' : 'parnu',
            'type' : ['/pizza' , '/restaurant'] ,

},

"steffani suve" : {
            'name': "Steffani Pizza Suve",
            #'openedEn': "Mon-Sun 11:00-24:00",
            #'openedEt': "E-P 11:00-24:00",
            #'openedRu': "Пн-Сб 12:00-23:00; Вс - Закрыто",
            'address': "Ranna pst 1",
            'latitude': "58.3754485",
            'longitude' : '24.4950857',
            'image': "http://i0.wp.com/steffani.ee/wp-content/uploads/2015/05/nom_8927.jpg",
            'priority': 100,
            'phone' : '+3724452228',
            'link' : 'http://steffani.ee/et/esileht/',
            'town' : 'parnu',
            'type' : ['/pizza'],

},

"piccadilly" : {
            'name': "Piccadilly",
            #'openedEn': "Mon-Sun 11:00-24:00",
            #'openedEt': "E-P 11:00-24:00",
            #'openedRu': "Пн-Сб 12:00-23:00; Вс - Закрыто",
            'address': "Pühavaimu 15",
            'latitude': "58.3843183",
            'longitude' : '24.4989849',
            'image': "http://toidujaht.ee/wp-content/uploads/2017/10/15393016_10154811927828684_2373874921353117774_o.jpg",
            'priority': 100,
            'phone' : '+3724420085',
            'link' : 'http://wine.kohvila.com/',
            'town' : 'parnu',
            'type' : ['/cafe' , '/whine'] ,

},

"noot" : {
            'name': "Restaurant Noot",
            'openedEn': "Mon-Sun 12:00-23:00",
            'openedEt': "E-P 12:00-23:00",
            'openedRu': "Пн-Вс 12:00-23:00",
            'address': "A.H.Tammsaare pst. 4A/6",
            'latitude': "58.3779514",
            'longitude' : '24.4985629',
            'image': "http://www.spaestonia.ee/resort/wp-content/uploads/2014/11/nootpart750x500.jpg",
            'priority': 100,
            'phone' : '+3724401012',
            'link' : 'http://www.spaestonia.ee/resort/en/restaurant/',
            'town' : 'parnu',
            'type' : ['/restaurant' , '/whine'] ,

},

"kalamajakas" : {
            'name': "Kalamajakas",
            #'openedEn': "Mon-Sun 11:00-23:00",
            #'openedEt': "E-P 11:00-23:00",
            #'openedRu': "Пн-Вс 11:00-23:00",
            'address': "Nikolai 24",
            'latitude': "58.3779597",
            'longitude' : '24.4963742',
            'image': "https://static1.visitestonia.com/images/3117173/Kalamajaka+kohvik_.jpg",
            'priority': 100,
            'phone' : '+37256854800',
            'link' : 'http://kalamajakas.ee/',
            'town' : 'parnu',
            'type' : '/restaurant',

},

"piparmunt" : {
            'name': "Piparmünt",
            'openedEn': "Mon-Sun 12:00-23:00",
            'openedEt': "E-P 12:00-23:00",
            'openedRu': "Пн-Вс 12:00-23:00",
            'address' : "Papli 13",
            'latitude' : "",
            'longitude'  : '',
            'image': "",
            'priority' : 100,
            'phone' : '+3724425736',
            'link' : 'http://wesset.ee/',
            '@' : '@piparmunt',
            'town' : 'parnu',
            'type' : '/restaurant',

},

"sweet rosie" : {
            'name': "Sweet Rosie",
            #'openedEn': "Mon-Sun 11:00-23:00",
            #'openedEt': "E-P 11:00-23:00",
            #'openedRu': "Пн-Вс 12:00-23:00",
            'address' : "Munga 2",
            'latitude' : "",
            'longitude'  : '',
            'image': "",
            'priority' : 100,
            'phone' : '+3724471471',
            'link' : 'http://wesset.ee/',
            '@' : '@sweetrosie',
            'town' : 'parnu',
            'type' : '/pub',

},

"mon ami" : {
            'name': "Mon Ami",
            'openedEn': "Sun-Thu 12:00-23:00 Fri-Sat 12:00-24:00",
            'openedEt': "p-N 12:00-23:00 R-L 12:00-24:00",
            'openedRu': "Вс-Чт 12:00-23:00 Пт-Сб 12:00-24:00",
            'address' : "Munga 2",
            'latitude' : "",
            'longitude'  : '',
            'image': "",
            'priority' : 100,
            'phone' : '+37258669990',
            'link' : 'http://wesset.ee/',
            '@' : '@monami',
            'town' : 'parnu',
            'type' : '/restaurant',

},

"mum cafe" : {
            'name': "Mum Cafe",
            #'openedEn': "Mon-Sun 11:00-23:00",
            #'openedEt': "E-P 11:00-23:00",
            #'openedRu': "Пн-Вс 12:00-23:00",
            'address' : "Pühavaimu 15",
            'latitude' : "",
            'longitude'  : '',
            'image': "",
            'priority' : 100,
            'phone' : '+372446555', #проверить
            'link' : 'http://wesset.ee/',
            '@' : '@mum',
            'town' : 'parnu',
            'type' : '/cafe',

},

"kolhethi" : {
            'name': "Kolhethi",
            #'openedEn': "Mon-Sun 11:00-23:00",
            #'openedEt': "E-P 11:00-23:00",
            #'openedRu': "Пн-Вс 12:00-23:00",
            'address' : "Kuninga 36",
            'latitude' : "",
            'longitude'  : '',
            'image': "",
            'priority' : 100,
            'phone' : '+37256296555',
            'link' : 'http://wesset.ee/',
            '@' : '@kolhethi',
            'town' : 'parnu',
            'type' : '/restaurant',
},

"postipoiss" : {
            'name': "Postipoiss Trahter",
            #'openedEn': "Sun-Thu 12:00-24:00 Fri-Sat 12:00-02:00",
            #'openedEt': "P-N 12:00-24:00 R-L 12:00-02:00",
            #'openedRu': "Вс-Чт 12:00-24:00 Пт-Сб 12:00-02:00",
            'address' : "Vee 12",
            'latitude' : "",
            'longitude'  : '',
            'image': "",
            'priority' : 100,
            'phone' : '+3724464864',
            'link' : 'http://wesset.ee/',
            '@' : '@postipoiss',
            'town' : 'parnu',
            'type' : '/restaurant',
},

"nikolai lehtla" : {
            'name': "Nikolai Lehtla",
            #'openedEn': "Sun-Thu 12:00-24:00 Fri-Sat 12:00-02:00",
            #'openedEt': "P-N 12:00-24:00 R-L 12:00-02:00",
            #'openedRu': "Вс-Чт 12:00-24:00 Пт-Сб 12:00-02:00",
            'address' : "Nikolai 7",
            'latitude' : "",
            'longitude'  : '',
            'image': "",
            'priority' : 100,
            'phone' : '+3724477366',
            'link' : 'http://wesset.ee/',
            '@' : '@nikolailehtla',
            'town' : 'parnu',
            'type' : '/restaurant',
},

"kroon" : {
            'name': "Kroon",
            #'openedEn': "Sun-Thu 12:00-24:00 Fri-Sat 12:00-02:00",
            #'openedEt': "P-N 12:00-24:00 R-L 12:00-02:00",
            #'openedRu': "Вс-Чт 12:00-24:00 Пт-Сб 12:00-02:00",
            'address' : "Ria mnt 71",
            'latitude' : "",
            'longitude'  : '',
            'image': "",
            'priority' : 100,
            'phone' : '+37256678190',
            'link' : 'http://wesset.ee/',
            '@' : '@kroon',
            'town' : 'parnu',
            'type' : '/restaurant'
},

"rannahotell" : {
            'name': "Rannahotel",
            #'openedEn': "Sun-Thu 12:00-24:00 Fri-Sat 12:00-02:00",
            #'openedEt': "P-N 12:00-24:00 R-L 12:00-02:00",
            #'openedRu': "Вс-Чт 12:00-24:00 Пт-Сб 12:00-02:00",
            'address' : 'Ranna pst 5',
            'latitude' : "",
            'longitude'  : '',
            'image': "",
            'priority' : 100,
            'phone' : '+3724444444',
            'link' : 'http://wesset.ee/',
            '@' : '@rannahotel',
            'town' : 'parnu',
            'type' : '/restaurant',
},

"da vince" : {
            'name': "Da Vince",
            'openedEn': "Mon-Sun 10:00-20:00",
            'openedEt': "E-P 10:00-20:00",
            'openedRu': "Пн-Вс 10:00-20:00",
            'address' : "Papiniidu 8/10",
            'latitude' : "",
            'longitude'  : '',
            'image': "",
            'priority' : 100,
            'phone' : '+3724455237',
            'link' : 'http://wesset.ee/',
            '@' : '@davince',
            'town' : 'parnu',
            'type' : '/restaurant',
},

"mack bbq" : {
            'name': "Mack Bar-BBQ",
            'openedEn': "Mon-Sun 10:00-20:00",
            'openedEt': "E-P 10:00-20:00",
            'openedRu': "Пн-Вс 10:00-20:00",
            'address' : "Supeluse 23A",
            'latitude' : "",
            'longitude'  : '',
            'image': "",
            'priority' : 100,
            'phone' : '+3725143472',
            'link' : 'http://wesset.ee/',
            '@' : '@davince',
            'town' : 'parnu',
            'type' : ['/restaurant' , '/bbq' , 'bar'] ,
},

"da vince" : {
            'name': "Da Vince",
            #'openedEn': "Mon-Sun 10:00-20:00",
            #'openedEt': "E-P 10:00-20:00",
            #'openedRu': "Пн-Вс 10:00-20:00",
            'address' : "Papiniidu 8/10",
            'latitude' : "",
            'longitude'  : '',
            'image': "",
            'priority' : 100,
            'phone' : '+3724455237',
            'link' : 'http://wesset.ee/',
            '@' : '@davince',
            'town' : 'parnu',
            'type' : ['/restaurant'],
},

"ahoy" : {
            'name': "AHOY Sushi",
            #'openedEn': "Mon-Sun 10:00-20:00",
            #'openedEt': "E-P 10:00-20:00",
            #'openedRu': "Пн-Вс 10:00-20:00",
            'address' : "Kuninga 34",
            'latitude' : "",
            'longitude'  : '',
            'image': "",
            'priority' : 100,
            'phone' : '+3724438543',
            'link' : 'http://wesset.ee/',
            '@' : '@ahoy',
            'town' : 'parnu',
            'type' : ['/sushi'],
},

"hahn pub" : {
            'name': "C.F. Hahn Pub",
            #'openedEn': "Mon-Sun 10:00-20:00",
            #'openedEt': "E-P 10:00-20:00",
            #'openedRu': "Пн-Вс 10:00-20:00",
            'address' : "Riia mnt 129A",
            'latitude' : "",
            'longitude'  : '',
            'image': "",
            'priority' : 100,
            'phone' : '+3724471909',
            'link' : 'http://wesset.ee/',
            '@' : '@hahnpub',
            'town' : 'parnu',
            'type' : ['/restaurant' , '/pub'],
},

"cafe grand" : {
            'name': "Cafe Grand",
            #'openedEn': "Mon-Sun 10:00-20:00",
            #'openedEt': "E-P 10:00-20:00",
            #'openedRu': "Пн-Вс 10:00-20:00",
            'address' : "Kuninga 25",
            'latitude' : "",
            'longitude'  : '',
            'image': "",
            'priority' : 100,
            'phone' : '+3724443412',
            'link' : 'http://wesset.ee/',
            '@' : '@grandcafe',
            'town' : 'parnu',
            'type' : ['/cafe'] ,
},

"sushi king" : {
            'name': "Sushi King",
            #'openedEn': "Mon-Sun 10:00-20:00",
            #'openedEt': "E-P 10:00-20:00",
            #'openedRu': "Пн-Вс 10:00-20:00",
            'address' : "Hommiku 3",
            'latitude' : "",
            'longitude'  : '',
            'image': "",
            'priority' : 100,
            'phone' : '+3725575555',
            'link' : 'http://wesset.ee/',
            '@' : '@sushiking',
            'town' : 'parnu',
            'type' : ['/sushi'] ,
},

"kaks pulka" : {
            'name': "Kaks Pulka",
            #'openedEn': "Mon-Sun 10:00-20:00",
            #'openedEt': "E-P 10:00-20:00",
            #'openedRu': "Пн-Вс 10:00-20:00",
            'address' : "A.H.Tammsaare pst 18",
            'latitude' : "",
            'longitude'  : '',
            'image': "",
            'priority' : 100,
            'phone' : '+37258183026',
            'link' : 'http://wesset.ee/',
            '@' : '@kakspulka',
            'town' : 'parnu',
            'type' : ['/sushi'] ,
},

"passion cafe" : {
            'name': "Passion Cafe",
            #'openedEn': "Mon-Sun 10:00-20:00",
            #'openedEt': "E-P 10:00-20:00",
            #'openedRu': "Пн-Вс 10:00-20:00",
            'address' : "Hospidali 14",
            'latitude' : "",
            'longitude'  : '',
            'image': "",
            'priority' : 100,
            'phone' : '+3724426202',
            'link' : 'http://wesset.ee/',
            'town' : 'parnu',
            'type' : ['/cafe'],
},

"paradiis" : {
            'name': "Restaurant Paradiis",
            #'openedEn': "Mon-Sun 10:00-20:00",
            #'openedEt': "E-P 10:00-20:00",
            #'openedRu': "Пн-Вс 10:00-20:00",
            'address' : "Riia mnt 57",
            'latitude' : "",
            'longitude'  : '',
            'image': "",
            'priority' : 100,
            'phone' : '+3724464633',
            'link' : 'http://wesset.ee/',
            'town' : 'parnu',
            'type' : ['/restaurant'],
},

"hobe taldrik" : {
            'name': "Hõbe Taldrik",
            #'openedEn': "Mon-Sun 10:00-20:00",
            #'openedEt': "E-P 10:00-20:00",
            #'openedRu': "Пн-Вс 10:00-20:00",
            'address' : "Suur-Sepa 18",
            'latitude' : "",
            'longitude'  : '',
            'image': "",
            'priority' : 100,
            'phone' : '+3724450505',
            'link' : 'http://wesset.ee/',
            'town' : 'parnu',
            'type' : ['/asia'],
},

"ephesus" : {
            'name': "Ephesus",
            #'openedEn': "Mon-Sun 10:00-20:00",
            #'openedEt': "E-P 10:00-20:00",
            #'openedRu': "Пн-Вс 10:00-20:00",
            'address' : "Rüütli 38",
            'latitude' : "",
            'longitude'  : '',
            'image': "",
            'priority' : 100,
            'phone' : '+3724427557',
            'link' : 'http://wesset.ee/',
            'town' : 'parnu',
            'type' : ['/restaurant', '/greek'],
},

"strand" : {
            'name': "Strand Restaurant",
            #'openedEn': "Mon-Sun 10:00-20:00",
            #'openedEt': "E-P 10:00-20:00",
            #'openedRu': "Пн-Вс 10:00-20:00",
            'address' : "A.H.Tammsaare pst 18",
            'latitude' : "",
            'longitude'  : '',
            'image': "",
            'priority' : 100,
            'phone' : '+3724475370',
            'link' : 'http://wesset.ee/',
            'town' : 'parnu',
            'type' : ['/restaurant'],
},

"pizza hunt" : {
            'name': "Pizza Hunt",
            #'openedEn': "Mon-Sun 10:00-20:00",
            #'openedEt': "E-P 10:00-20:00",
            #'openedRu': "Пн-Вс 10:00-20:00",
            'address' : "Supeluse 3",
            'latitude' : "",
            'longitude'  : '',
            'image': "",
            'priority' : 100,
            'phone' : '+3724434023',
            'link' : 'http://wesset.ee/',
            'town' : 'parnu',
            'type' : ['/pizza'],
},

"everest" : {
            'name': "Mt. Everest",
            #'openedEn': "Mon-Sun 10:00-20:00",
            #'openedEt': "E-P 10:00-20:00",
            #'openedRu': "Пн-Вс 10:00-20:00",
            'address' : "Rüütli 44",
            'latitude' : "",
            'longitude'  : '',
            'image': "",
            'priority' : 100,
            'phone' : '+3724464359',
            'link' : 'http://wesset.ee/',
            'town' : 'parnu',
            'type' : ['/asia'],
},

"baby back" : {
            'name': "Baby Back Ribs & BBQ",
            #'openedEn': "Mon-Sun 10:00-20:00",
            #'openedEt': "E-P 10:00-20:00",
            #'openedRu': "Пн-Вс 10:00-20:00",
            'address' : "Papiniidu 8/10",
            'latitude' : "",
            'longitude'  : '',
            'image': "",
            'priority' : 100,
            'phone' : '+3724422023',
            'link' : 'http://wesset.ee/',
            'town' : 'parnu',
            'type' : ['/restaurant' , '/bbq'],
},

"embecke" : {
            'name': "Embecke",
            #'openedEn': "Mon-Sun 10:00-20:00",
            #'openedEt': "E-P 10:00-20:00",
            #'openedRu': "Пн-Вс 10:00-20:00",
            'address' : "Rüütli 44",
            'latitude' : "",
            'longitude'  : '',
            'image': "",
            'priority' : 100,
            'phone' : '+3724478900',
            'link' : 'http://wesset.ee/',
            'town' : 'parnu',
            'type' : ['/restaurant' , '/cafe'],
},


"romantic bar" : {
            'name': "Romantic Bar",
            #'openedEn': "Mon-Sun 10:00-20:00",
            #'openedEt': "E-P 10:00-20:00",
            #'openedRu': "Пн-Вс 10:00-20:00",
            'address' : "Side tn 14",
            'latitude' : "",
            'longitude'  : '',
            'image': "",
            'priority' : 100,
            'phone' : '+3724451625',
            'link' : 'http://wesset.ee/',
            'town' : 'parnu',
            'type' : ['/bar'],
},

"oregano" : {
            'name': "Oregano",
            #'openedEn': "Mon-Sun 10:00-20:00",
            #'openedEt': "E-P 10:00-20:00",
            #'openedRu': "Пн-Вс 10:00-20:00",
            'address' : "Saeaese 7",
            'latitude' : "",
            'longitude'  : '',
            'image': "",
            'priority' : 100,
            'phone' : '+3725206701',
            'link' : 'http://wesset.ee/',
            'town' : 'parnu',
            'type' : ['/restaurant' , '/greek'],
},

"pecadello" : {
            'name': "Cafe Pecadello",
            'openedEn': "Mon-Sun 10:00-20:00" ,
            'openedEt': "E-P 10:00-20:00",
            'openedRu': "Пн-Вс 10:00-20:00",
            'address' : "Papiniidu 8/10",
            'latitude' : "",
            'longitude'  : '',
            'image': "",
            'priority' : 100,
            'phone' : '+3724455927',
            'link' : 'http://wesset.ee/',
            'town' : 'parnu',
            'type' : ['/cafe'],
},

"jahtklub" : {
            'name': "Jahtklubi Restaurant",
            #'openedEn': "Mon-Sun 10:00-20:00",
            #'openedEt': "E-P 10:00-20:00",
            #'openedRu': "Пн-Вс 10:00-20:00",
            'address' : "Lootsi 6",
            'latitude' : "",
            'longitude'  : '',
            'image': "",
            'priority' : 100,
            'phone' : '+3724471760',
            'link' : 'http://wesset.ee/',
            'town' : 'parnu',
            'type' : ['/restaurant',]
},

"city pub" : {
            'name': "City Pub",
            #'openedEn': "Mon-Sun 10:00-20:00",
            #'openedEt': "E-P 10:00-20:00",
            #'openedRu': "Пн-Вс 10:00-20:00",
            'address' : "Hommiku 8",
            'latitude' : "",
            'longitude'  : '',
            'image': "",
            'priority' : 100,
            'phone' : '+37256894114',
            'link' : 'http://wesset.ee/',
            'town' : 'parnu',
            'type' : ['/pub' , '/bar'],
},

"buudha best" : {
            'name': "Buddha Best",
            #'openedEn': "Mon-Sun 10:00-20:00",
            #'openedEt': "E-P 10:00-20:00",
            #'openedRu': "Пн-Вс 10:00-20:00",
            'address' : "Tallinna mnt 70",
            'latitude' : "",
            'longitude'  : '',
            'image': "",
            'priority' : 100,
            'phone' : '+3724452440',
            'link' : 'http://wesset.ee/',
            'town' : 'parnu',
            'type' : ['/asia'],
},

"muuli bar" : {
            'name': "Muuli Bar",
            #'openedEn': "Mon-Sun 10:00-20:00",
            #'openedEt': "E-P 10:00-20:00",
            #'openedRu': "Пн-Вс 10:00-20:00",
            'address' : "Seedri 6",
            'latitude' : "",
            'longitude'  : '',
            'image': "",
            'priority' : 100,
            'phone' : '+3724450111',
            'link' : 'http://wesset.ee/',
            'town' : 'parnu',
            'type' : ['/bar'],
},

"armeenia restoran" : {
            'name': "Armeenia Restoran",
            #'openedEn': "Mon-Sun 10:00-20:00",
            #'openedEt': "E-P 10:00-20:00",
            #'openedRu': "Пн-Вс 10:00-20:00",
            'address' : "Kuninga 17",
            'latitude' : "",
            'longitude'  : '',
            'image': "",
            'priority' : 100,
            'phone' : '+37255580025',
            'link' : 'http://wesset.ee/',
            'town' : 'parnu',
            'type' : ['/restaurant' , '/grill'],
},

"kuursaal" : {
            'name': "Kuursaal",
            #'openedEn': "Mon-Sun 10:00-20:00",
            #'openedEt': "E-P 10:00-20:00",
            #'openedRu': "Пн-Вс 10:00-20:00",
            'address' : "Mere puiestee 22",
            'latitude' : "",
            'longitude'  : '',
            'image': "",
            'priority' : 100,
            'phone' : '+37258100165',
            'link':'',
            'town' : 'parnu',
            'type' : ['/restaurant' , '/pub' , '/bar'],
},

"white beach" : {
            'name': "White Beach Golf",
            #'openedEn': "Mon-Sun 10:00-20:00",
            #'openedEt': "E-P 10:00-20:00",
            #'openedRu': "Пн-Вс 10:00-20:00",
            'address' : "Valgeranna Küla",
            'latitude' : "",
            'longitude'  : '',
            'image': "",
            'priority' : 100,
            'phone' : '+3724429930',
            'link' : 'http://wesset.ee/',
            'town' : 'parnu',
            'type' : ['/restaurant'],
},

"bumerang" : {
            'name': "Bumerang",
            #'openedEn': "Mon-Sun 10:00-20:00",
            #'openedEt': "E-P 10:00-20:00",
            #'openedRu': "Пн-Вс 10:00-20:00",
            'address' : "SRingi 37",
            'latitude' : "",
            'longitude'  : '',
            'image': "",
            'priority' : 100,
            'phone' : '+3724420302',
            'link' : 'http://wesset.ee/',
            'town' : 'parnu',
            'type' : ['/pub'],
},

"bum-bum" : {
            'name': "Bum-Bum",
            #'openedEn': "Mon-Sun 10:00-20:00",
            #'openedEt': "E-P 10:00-20:00",
            #'openedRu': "Пн-Вс 10:00-20:00",
            'address' : "Kuninga 1",
            'latitude' : "",
            'longitude'  : '',
            'image': "",
            'priority' : 100,
            'phone' : '+3726080588',
            'link' : 'http://wesset.ee/',
            '@' : '@bumbum',
            'town' : 'parnu',
            'type' : '/pub',
},

"yolo" : {
            'name': "Y.O.L.O GastroPub",
            #'openedEn': "Mon-Sun 10:00-20:00",
            #'openedEt': "E-P 10:00-20:00",
            #'openedRu': "Пн-Вс 10:00-20:00",
            'address' : "Ringi 37",
            'latitude' : "",
            'longitude'  : '',
            'image': "",
            'priority' : 100,
            'phone' : '+3726007275',
            'link' : 'http://wesset.ee/',
            '@' : '@yolo',
            'town' : 'parnu',
            'type' : ['/pub'],
},

"buffalo" : {
            'name': "Buffalo Grill",
            #'openedEn': "Mon-Sun 10:00-20:00",
            #'openedEt': "E-P 10:00-20:00",
            #'openedRu': "Пн-Вс 10:00-20:00",
            'address' : "Rüütli 14",
            'latitude' : "",
            'longitude'  : '',
            'image': "",
            'priority' : 100,
            'phone' : '+3724456555',
            'link' : 'http://wesset.ee/',
            'town' : 'parnu',
            'type' : ['/grill' , '/restaurant'],
},

"asian village" : {
            'name': "Asian Village",
            #'openedEn': "Mon-Sun 10:00-20:00",
            #'openedEt': "E-P 10:00-20:00",
            #'openedRu': "Пн-Вс 10:00-20:00",
            'address' : "Ranna pst 1d",
            'latitude' : "",
            'longitude'  : '',
            'image': "",
            'priority' : 100,
            'phone' : '+3724464891',
            'link' : 'http://wesset.ee/',
            'town' : 'parnu',
            'type' : ['/asia'],
},
"rannakohvik" : {
            'name': "RannaKohvik",
            #'openedEn': "Mon-Sun 10:00-20:00",
            #'openedEt': "E-P 10:00-20:00",
            #'openedRu': "Пн-Вс 10:00-20:00",
            'address' : "Ranna pst 1d",
            'latitude' : "",
            'longitude'  : '',
            'image': "",
            'priority' : 100,
            'phone' : '+37264891',
            'link' : 'http://wesset.ee/',
            'town' : 'parnu',
            'type' : ['/cafe'],
},

"eagle golf" : {
            'name': "Eagle Golf Restaurant",
            #'openedEn': "Mon-Sun 10:00-20:00",
            #'openedEt': "E-P 10:00-20:00",
            #'openedRu': "Пн-Вс 10:00-20:00",
            'address' : "Klubi tee 1 | Tahkuranna",
            'latitude' : "",
            'longitude'  : '',
            'image': "",
            'priority' : 100,
            'phone' : '+3724433030',
            'link' : 'http://wesset.ee/',
            'town' : 'parnu',
            'type' : ['/restaurant'],
},

"kentuki lovi" : {
            'name': "Kentuki Lõvi",
            #'openedEn': "Mon-Sun 10:00-20:00",
            #'openedEt': "E-P 10:00-20:00",
            #'openedRu': "Пн-Вс 10:00-20:00",
            'address' : "Tallinna mnt 12",
            'latitude' : "",
            'longitude'  : '',
            'image': "",
            'priority' : 100,
            'phone' : '+3724436202',
            'link' : 'http://wesset.ee/',
            'town' : 'parnu',
            'type' : ['/pub'],
},

"ruutlihoov" : {
            'name': "Eagle Golf Restaurant",
            #'openedEn': "Mon-Sun 10:00-20:00",
            #'openedEt': "E-P 10:00-20:00",
            #'openedRu': "Пн-Вс 10:00-20:00",
            'address' : "Rüütli 29",
            'latitude' : "",
            'longitude'  : '',
            'image': "",
            'priority' : 100,
            'phone' : '+3724431439',
            'link' : 'http://wesset.ee/',
            'town' : 'parnu',
            'type' : ['/pub'],
},

"vaga mama" : {
            'name': "Vaga Mama",
            #'openedEn': "Mon-Sun 10:00-20:00",
            #'openedEt': "E-P 10:00-20:00",
            #'openedRu': "Пн-Вс 10:00-20:00",
            'address' : "Rüütli 39",
            'latitude' : "",
            'longitude'  : '',
            'image': "",
            'priority' : 100,
            'phone' : '+37258553339',
            'link' : 'http://wesset.ee/',
            'town' : 'parnu',
            'type' : ['/asia'],
},

"monus margarita" : {
            'name': "Mõnus Margarita",
            #'openedEn': "Mon-Sun 10:00-20:00",
            #'openedEt': "E-P 10:00-20:00",
            #'openedRu': "Пн-Вс 10:00-20:00",
            'address' : "Akadeemia 5",
            'latitude' : "",
            'longitude'  : '',
            'image': "",
            'priority' : 100,
            'phone' : '+3724430929',
            'link' : 'http://wesset.ee/',
            'town' : 'parnu',
            'type' : ['/restaurant'],
},

"neptun" : {
            'name': "Side 14A",
            #'openedEn': "Mon-Sun 10:00-20:00",
            #'openedEt': "E-P 10:00-20:00",
            #'openedRu': "Пн-Вс 10:00-20:00",
            'address' : "Side 14A",
            'latitude' : "",
            'longitude'  : '',
            'image': "",
            'priority' : 100,
            'phone' : '+3724479466',
            'link' : 'http://wesset.ee/',
            'town' : 'parnu',
            'type' : ['/grill'],
},

"la boca" : {
            'name': "La Boca",
            #'openedEn': "Mon-Sun 10:00-20:00",
            #'openedEt': "E-P 10:00-20:00",
            #'openedRu': "Пн-Вс 10:00-20:00",
            'address' : "Nikolai 13",
            'latitude' : "",
            'longitude'  : '',
            'image': "",
            'priority' : 100,
            'phone' : '+3724420061',
            'link' : 'http://wesset.ee/',
            'town' : 'parnu',
            'type' : ['/restaurant'],
},

"sheriff saloon" : {
            'name': "Sheriff Saloon Burger & Steakhouse",
            #'openedEn': "Mon-Sun 10:00-20:00",
            #'openedEt': "E-P 10:00-20:00",
            #'openedRu': "Пн-Вс 10:00-20:00",
            'address' : "Gildi 7",
            'latitude' : "",
            'longitude'  : '',
            'image': "",
            'priority' : 100,
            'phone' : '+3724433030',
            'link' : 'http://wesset.ee/',
            'town' : 'parnu',
            'type' : ['/restaurant' , '/burger' , '/bbq'],
},

}

inline = {}